config/routes.rb
Rails.application.routes.draw do
  resources :dives
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root to: "home#index"
  root 'dives#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dive.rb
class Dive < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :dives
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def index
    @dives = Dive.where(user: current_user).all
  end
end

app/controllers/dives_controller.rb
class DivesController < ApplicationController
  before_action :set_dife, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /dives
  # GET /dives.json
  def index
    @dives = Dive.where(user: current_user).all
  end

  # GET /dives/1
  # GET /dives/1.json
  def show
  end

  # GET /dives/new
  def new
    @dife = Dive.new
  end

  # GET /dives/1/edit
  def edit
  end

  # POST /dives
  # POST /dives.json
  def create
    @dife = Dive.new(dife_params)
    @dife.user = current_user

    respond_to do |format|
      if @dife.save
        format.html { redirect_to @dife, notice: 'Dive was successfully created.' }
        format.json { render :show, status: :created, location: @dife }
      else
        format.html { render :new }
        format.json { render json: @dife.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dives/1
  # PATCH/PUT /dives/1.json
  def update
    respond_to do |format|
      if @dife.update(dife_params)
        format.html { redirect_to @dife, notice: 'Dive was successfully updated.' }
        format.json { render :show, status: :ok, location: @dife }
      else
        format.html { render :edit }
        format.json { render json: @dife.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dives/1
  # DELETE /dives/1.json
  def destroy
    @dife.destroy
    respond_to do |format|
      format.html { redirect_to dives_url, notice: 'Dive was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dife
      @dife = Dive.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dife_params
      # params.require(:dife).permit(:location, :timeSecounds, :maxDepth, :lat, :lon, :date, :notes)
      params.permit(:location, :timeSecounds, :maxDepth, :lat, :lon, :date, :notes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dives_helper.rb
module DivesHelper
end

app/views/dives/_form.html.erb
<%= form_with(model: dife, local: true) do |form| %>
  <% if dife.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dife.errors.count, "error") %> prohibited this dife from being saved:</h2>

      <ul>
        <% dife.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :timeSecounds %>
    <%= form.number_field :timeSecounds %>
  </div>

  <div class="field">
    <%= form.label :maxDepth %>
    <%= form.text_field :maxDepth %>
  </div>

  <div class="field">
    <%= form.label :lat %>
    <%= form.text_field :lat %>
  </div>

  <div class="field">
    <%= form.label :lon %>
    <%= form.text_field :lon %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_area :notes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dives/edit.html.erb
<h1>Editing Dife</h1>

<%= render 'form', dife: @dife %>

<%= link_to 'Show', @dife %> |
<%= link_to 'Back', dives_path %>

app/views/dives/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dives</h1>

<table>
  <thead>
    <tr>
      <th>Location</th>
      <th>Timesecounds</th>
      <th>Maxdepth</th>
      <th>Lat</th>
      <th>Lon</th>
      <th>Date</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dives.each do |dife| %>
      <tr>
        <td><%= dife.location %></td>
        <td><%= dife.timeSecounds %></td>
        <td><%= dife.maxDepth %></td>
        <td><%= dife.lat %></td>
        <td><%= dife.lon %></td>
        <td><%= dife.date %></td>
        <td><%= dife.notes %></td>
        <td><%= link_to 'Show', dife %></td>
        <td><%= link_to 'Edit', edit_dife_path(dife) %></td>
        <td><%= link_to 'Destroy', dife, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dife', new_dife_path %>

app/views/dives/new.html.erb
<h1>New Dife</h1>

<%= render 'form', dife: @dife %>

<%= link_to 'Back', dives_path %>

app/views/dives/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Location:</strong>
  <%= @dife.location %>
</p>

<p>
  <strong>Timesecounds:</strong>
  <%= @dife.timeSecounds %>
</p>

<p>
  <strong>Maxdepth:</strong>
  <%= @dife.maxDepth %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @dife.lat %>
</p>

<p>
  <strong>Lon:</strong>
  <%= @dife.lon %>
</p>

<p>
  <strong>Date:</strong>
  <%= @dife.date %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @dife.notes %>
</p>

<%= link_to 'Edit', edit_dife_path(@dife) %> |
<%= link_to 'Back', dives_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Divelog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </head>

  <body>
  <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
    <h5 class="my-0 mr-md-auto font-weight-normal">Divelog.me</h5>
    <nav class="my-2 my-md-0 mr-md-3">
      <a class="p-2 text-dark" href="#">Features</a>
<!--      <a class="p-2 text-dark" href="#">Enterprise</a>-->
<!--      <a class="p-2 text-dark" href="#">Support</a>-->
<!--      <a class="p-2 text-dark" href="#">Pricing</a>-->
    </nav>
    <% if current_user %>
      <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
    <% else %>
      <%= link_to('Login', new_user_session_path) %>
    <% end %>
  </div>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>